BaytonicECommerce/Controllers/AdminCategoryController.cs
using BaytonicECommerce.Models;
using BaytonicECommerce.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BaytonicECommerce.ViewModels;
using Newtonsoft.Json;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;

namespace BaytonicECommerce.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class AdminCategoryController : BaseController
    {
        private readonly ICategoryRepository categoryRepository;
        private readonly ILogger<AdminCategoryController> _logger;

        public AdminCategoryController(ICategoryRepository _categoryRepository, ILogger<AdminCategoryController> logger)
        {
             categoryRepository = _categoryRepository;
            _logger = logger;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> Categories = categoryRepository.GetAll();
            return View(Categories);
        }
        [HttpGet]
        public IActionResult Create()
        {
            Category_ParentVM category_ParentVM = new Category_ParentVM();
            category_ParentVM.Categories= categoryRepository.GetAll();
            return View(category_ParentVM);
        }

        [HttpPost]
        public IActionResult Create(Category_ParentVM category_Parent)
        {
            Category category = new Category();
            {
                category.NameE= category_Parent.category.NameE;
                category.NameA = category_Parent.category.NameA;
                category.ParentId = category_Parent.category.ParentId;
                category.IsActive = category_Parent.category.IsActive;
                category.ShowInHomePage = category_Parent.category.ShowInHomePage;

            }
            NotifyToastr("success", "Data saved successfully");
            categoryRepository.Insert(category);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult Edit(long id)
        {
            Category_ParentVM category_ParentVM = new Category_ParentVM();
            category_ParentVM.Categories = categoryRepository.GetAll();
            category_ParentVM.category = categoryRepository.GetById(id);
            return View(category_ParentVM);
        }
        [HttpPost]
        public IActionResult Edit(Category_ParentVM category_ParentVM)
        {
            category_ParentVM.Categories = categoryRepository.GetAll();
          
            Category category = categoryRepository.GetById(category_ParentVM.Categories.FirstOrDefault().Id);
            if (category!=null)
            {
                category.NameE = category_ParentVM.category.NameE;
                category.NameA = category_ParentVM.category.NameA;
                category.ParentId = category_ParentVM.category.ParentId;
                category.IsActive = category_ParentVM.category.IsActive;
                category.ShowInHomePage = category_ParentVM.category.ShowInHomePage;
            }
            NotifyToastr("success", "Data edited successfully");
            return View(category_ParentVM);
        }
        public IActionResult DeleteToRecycle(long id)
        {
            categoryRepository.DeleteToRecycle(id);

            return RedirectToAction("Index");

        }
        public IActionResult Delete(long id)
        {
            categoryRepository.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

BaytonicECommerce/Views/AdminCategory/Create.cshtml
@model Category_ParentVM
@{
    ViewData["Title"] = "Create Category";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container-fluid">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h5 style="color:gray">Categories</h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="AdminCategory">Categories</a></li>
                        <li class="breadcrumb-item active">Add New Category</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="card card-info" style="margin:20px">
        <div class="card-header">
            <h3 class="card-title">New Category</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" asp-controller="AdminCategory" method="post" asp-action="Create">
            <div class="card-body">
                <div class="form-group row">
                    <label asp-for="category.NameE" class="col-sm-2 col-form-label"> English Name</label>
                    <div class="col-sm-10">
                        <input asp-for="category.NameE" class="form-control" placeholder="Write English Name of Category" required>
                    </div>
                    <span asp-validation-for="category.NameE" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    <label asp-for="category.NameA" class="col-sm-2 col-form-label"> Arabic Name</label>
                    <div class="col-sm-10">
                        <input asp-for="category.NameA" class="form-control" placeholder="Write Arabic Name of Category" required>
                    </div>
                    <span asp-validation-for="category.NameA" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(x => Model.category, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.DropDownListFor(x => Model.category.ParentId, new SelectList(Model.Categories, "Id", "NameE"), "-- Select One--", htmlAttributes: new { @class = "form-control", id = "CategoryId" })
                    </div>
                    <span asp-validation-for="category.ParentId" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    <div class="custom-control custom-checkbox">
                        <input asp-for="category.ShowInHomePage" class="custom-control-input" type="checkbox" style="margin-right:10px">
                        <label asp-for="category.ShowInHomePage" class="custom-control-label">Show In Home Page</label>
                        <span asp-validation-for="category.ShowInHomePage" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="custom-control custom-checkbox">
                        <input asp-for="category.IsActive" class="custom-control-input" type="checkbox" style="margin-right:10px">
                        <label asp-for="category.IsActive" class="custom-control-label">Active</label>
                        <span asp-validation-for="category.IsActive" class="text-danger"></span>
                    </div>

                </div>

            </div>


            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-info"> <i class="far fa-save mr-1"></i> Save</button>
                <a asp-action="Index" asp-controller="AdminCategory" class="btn btn-default float-right">Cancel</a>
            </div>

            <!-- /.card-footer -->
        </form>
    </div>
</div>

BaytonicECommerce/Views/AdminCategory/Edit.cshtml
@model Category_ParentVM
@{
    ViewData["Title"] = "Edit Category";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container-fluid">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h5 style="color:gray">Categories</h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="AdminCategory">Categories</a></li>
                        <li class="breadcrumb-item active">Edit Category</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="card card-info" style="margin:20px">
        <div class="card-header">
            <h3 class="card-title">Edit Category</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" asp-controller="AdminCategory" method="post" asp-action="Edit">
            <div class="card-body">
                <div class="form-group row">
                    <label asp-for="category.NameE" class="col-sm-2 col-form-label"> English Name</label>
                    <div class="col-sm-10">
                        <input asp-for="category.NameE" class="form-control" placeholder="Write English Name of Category" required>
                    </div>
                    <span asp-validation-for="category.NameE" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    <label asp-for="category.NameA" class="col-sm-2 col-form-label"> Arabic Name</label>
                    <div class="col-sm-10">
                        <input asp-for="category.NameA" class="form-control" placeholder="Write Arabic Name of Category" required>
                    </div>
                    <span asp-validation-for="category.NameA" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(x => Model.category, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.DropDownListFor(x => Model.category.ParentId, new SelectList(Model.Categories, "Id", "NameE"), htmlAttributes: new { @class = "form-control", id = "CategoryId" })
                    </div>
                    <span asp-validation-for="category.ParentId" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    <div class="custom-control custom-checkbox">
                        <input asp-for="category.ShowInHomePage" class="custom-control-input" type="checkbox" style="margin-right:10px">
                        <label asp-for="category.ShowInHomePage" class="custom-control-label">Show In Home Page</label>
                        <span asp-validation-for="category.ShowInHomePage" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="custom-control custom-checkbox">
                        <input asp-for="category.IsActive" class="custom-control-input" type="checkbox" style="margin-right:10px">
                        <label asp-for="category.IsActive" class="custom-control-label">Active</label>
                        <span asp-validation-for="category.IsActive" class="text-danger"></span>
                    </div>

                </div>

            </div>


            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-info"> <i class="far fa-save mr-1"></i> Save</button>
                <a asp-action="Index" asp-controller="AdminCategory" class="btn btn-default float-right">Cancel</a>
            </div>

            <!-- /.card-footer -->
        </form>
    </div>
</div>

BaytonicECommerce/Views/AdminCategory/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@model IEnumerable<Category>
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h3 style="color:gray">Categories</h3>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active"></li>

                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div>
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">


                            <div class="row mb-3">
                                <div class="col-12">
                                    <div class="input-group input-group-lg">
                                        <input type="search" id="btnSearch" class="form-control form-control-sm" placeholder="Type your keywords here">
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-sm btn-default">
                                                <i class="fa fa-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <a asp-action="Create" asp-controller="AdminCategory" type="button" class="btn btn-info float-right btn-sm"> <i class="fas fa-plus"></i> New</a>

                                    <table id="example1" class="table table-bordered  table-striped mt-3">
                                        <thead class="table-primary">
                                            <tr>
                                                <th>Category English Name</th>
                                                <th>Category Arabic Name</th>
                                                <th>Parent</th>
                                                <th>IsActive</th>
                                                <th>#</th>
                                            </tr>
                                        </thead>
                                        <tbody id="tblProduct" class="table-sm">
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>@item.NameE</td>
                                                    <td>@item.NameA</td>
                                                    <td>@(item.ParentId == null ? item.NameE : item.Parent.NameE)</td>
                                                    <td>@item.IsActive</td>
                                                    <td>

                                                        <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
                                                            <i class="fa fa-ellipsis-h" aria-hidden="true"></i>
                                                        </a>
                                                        <div class="dropdown-menu" style="">
                                                            <a asp-action="Edit" asp-controller="AdminCategory" asp-route-id="@item.Id" class=" nav-link" tabindex="-1"><i class="fas fa-edit"></i> Edit</a>
                                                            <a asp-action="Delete" asp-controller="AdminCategory" asp-route-id="@item.Id" class=" nav-link" tabindex="-1" style="color:red"> <i class="far fa-trash-alt"></i> Delete</a>

                                                        </div>

                                                    </td>

                                                </tr>

                                            }
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
    </div>
    </div>

</section>
@section Scripts{
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false, "searching": false,
                buttons: [{
                    extend: 'excel',
                    text: ' Export',
                    title: 'All Categories',
                    className: 'btn btn-sm mr-1',
                    exportOptions: {
                        columns: 'th:not(:last-child)'
                    }
                }, {
                        extend: 'print',
                        text: 'print',
                        title: 'All Categories',
                        className: 'btn btn-sm mr-1',
                        exportOptions: {
                            columns: 'th:not(:last-child)'
                        }
                    }],
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        });
        $('#btnSearch').keyup(function () {
            search_table($(this).val());
        });
        function search_table(value) {
            $("#tblProduct tr").each(function () {
                var found = 'false';
                $(this).each(function () {
                    if ($(this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0) {
                        found = 'true';
                    }
                });
                if (found == 'true') {
                    $(this).show();
                } else {
                    $(this).hide();
                }
            });
            };
    </script>
}