BaytonicECommerce/Controllers/AdminGovernmentShippingController.cs
using BaytonicECommerce.Models;
using BaytonicECommerce.Repository;
using BaytonicECommerce.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BaytonicECommerce.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class AdminGovernmentShippingController : BaseController
    {

        private IGovernmentShippingRepository governmentShippingRepository;
        public AdminGovernmentShippingController(IGovernmentShippingRepository _governmentShippingRepository)
        {
            governmentShippingRepository=_governmentShippingRepository;
        }
        public IActionResult Index()
        {
            IEnumerable<GovernmentShipping> AllGovs = governmentShippingRepository.GetAll();
            return View(AllGovs);
        }
        [HttpGet]
        public IActionResult Create()
        {
      
            return View();
        }
        [HttpPost]
        public IActionResult Create(GovernmentShipping model)
        {
          
            governmentShippingRepository.Insert(model);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(long id)
        {
            GovernmentShipping gov = new GovernmentShipping();
            gov = governmentShippingRepository.GetById(id);
            return View(gov);
        }
        [HttpPost]
        public IActionResult Edit(GovernmentShipping model)
        {
          
            governmentShippingRepository.Update(model);
            return RedirectToAction("Index");
        }
      
        public IActionResult Delete(long id)
        {
            governmentShippingRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

BaytonicECommerce/Views/AdminGovernmentShipping/Create.cshtml
@model GovernmentShipping
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container-fluid">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h5 style="color:gray">Government Shipping</h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="AdminGovernmentShipping">Product-Offer</a></li>
                        <li class="breadcrumb-item active">Add New Government Shipping Quota</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="card card-info" style="margin:10px">
        <div class="card-header">
            <h3 class="card-title">New Shipping Quota</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" asp-controller="AdminGovernmentShipping" method="post" asp-action="Create">
            <div class="card-body">
                <div class="form-group row">
                    <label asp-for="Name" class="col-sm-2 col-form-label">Government Name</label>
                    <div class="col-sm-10">
                        <input asp-for="Name" type="text" class="form-control" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="ShippingPrice" class="col-sm-2 col-form-label">Shipping Price </label>
                    <div class="col-sm-9">
                        <input asp-for="ShippingPrice" class="form-control"  min="0" required>
                    </div>
                    <label class="col-sm-1 col-form-label">EGP </label>
                    <span asp-validation-for="ShippingPrice" class="text-danger"></span>
                </div>
               
                <div class="form-group row">
            <div class="custom-control custom-checkbox">
                <input asp-for="IsActive" class="custom-control-input" type="checkbox" style="margin-right:10px">
                <label asp-for="IsActive" class="custom-control-label">Active</label>
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>

        </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-info"> <i class="far fa-save mr-1"></i> Save</button>
                <a asp-action="Index" asp-controller="AdminGovernmentShipping" class="btn btn-default float-right">Cancel</a>
            </div>

            <!-- /.card-footer -->
        </form>
    </div>
</div>

BaytonicECommerce/Views/AdminGovernmentShipping/Edit.cshtml
@model GovernmentShipping
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container-fluid">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h5 style="color:gray">Government Shipping</h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="AdminGovernmentShipping">Product-Offer</a></li>
                        <li class="breadcrumb-item active">Add New Government Shipping Quota</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="card card-info" style="margin:10px">
        <div class="card-header">
            <h3 class="card-title">Edit Shipping Quota</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" asp-controller="AdminGovernmentShipping" method="post" asp-action="Edit">
            <div class="card-body">
                <div class="form-group row">
                    <label asp-for="Name" class="col-sm-2 col-form-label">Government Name</label>
                    <div class="col-sm-10">
                        <input asp-for="Name" type="text" class="form-control" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="ShippingPrice" class="col-sm-2 col-form-label">Shipping Price </label>
                    <div class="col-sm-9">
                        <input asp-for="ShippingPrice" class="form-control" min="0" required>
                    </div>
                    <label class="col-sm-1 col-form-label">EGP </label>
                    <span asp-validation-for="ShippingPrice" class="text-danger"></span>
                </div>

                <div class="form-group row">
                    <div class="custom-control custom-checkbox">
                        <input asp-for="IsActive" class="custom-control-input" type="checkbox" style="margin-right:10px">
                        <label asp-for="IsActive" class="custom-control-label">Active</label>
                        <span asp-validation-for="IsActive" class="text-danger"></span>
                    </div>

                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-info"> <i class="far fa-save mr-1"></i> Save</button>
                <a asp-action="Index" asp-controller="AdminGovernmentShipping" class="btn btn-default float-right">Cancel</a>
            </div>

            <!-- /.card-footer -->
        </form>
    </div>
</div>

BaytonicECommerce/Views/AdminGovernmentShipping/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@model IEnumerable<GovernmentShipping>
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h3 style="color:gray">Government Shipping </h3>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active">Government Shipping</li>

                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div>
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">


                            <div class="row mb-3">
                                <div class="col-12">
                                    <div class="input-group input-group-lg">
                                        <input type="search" id="btnSearch" class="form-control form-control-sm" placeholder="Type your keywords here">
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-sm btn-default">
                                                <i class="fa fa-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <a asp-action="Create" asp-controller="AdminGovernmentShipping" type="button" class="btn btn-info float-right btn-sm"> <i class="fas fa-plus"></i> New</a>

                                    <table id="example1" class="table table-bordered  table-striped mt-3 text-center">
                                        <thead class="table-primary">
                                            <tr>
                                                <th>Government Name</th>
                                                <th>Shipping quota</th>
                                                <th>Active</th>
                                                <th>#</th>
                                            </tr>
                                        </thead>
                                        <tbody id="tblGov" class="table-sm">
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>@item.Name</td>
                                                    <td>@item.ShippingPrice</td>
                                                    <td>
                                                        @if (item.IsActive)
                                                        {


                                                            <i class="fa fa-check text-success" aria-hidden="true"></i>
                                                        }
                                                        else
                                                        {
                                                            <i class="fa fa-times text-danger" aria-hidden="true"></i>
                                                        }
                                                    </td>
                                                    <td>

                                                        <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
                                                            <i class="fa fa-ellipsis-h" aria-hidden="true"></i>
                                                        </a>
                                                        <div class="dropdown-menu" style="">
                                                            <a asp-controller="AdminGovernmentShipping" asp-action="Edit" asp-route-id="@item.Id" class=" nav-link" tabindex="-1"><i class="fas fa-edit"></i> Edit</a>
                                                            <a asp-action="Delete" asp-controller="AdminGovernmentShipping" asp-route-id="@item.Id" class="nav-link" tabindex="-1" style="color:red"> <i class="far fa-trash-alt"></i> Delete</a>

                                                        </div>

                                                    </td>

                                                </tr>

                                            }
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
    </div>
    @*</div>*@

</section>
@section Scripts{
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false, "searching": false,
                buttons: [{
                    extend: 'excel',
                    text: ' Export',
                    title: 'All Products',
                    className: 'btn btn-sm mr-1',
                    exportOptions: {
                        columns: 'th:not(:last-child)'
                    }
                }, {
                    extend: 'print',
                    text: 'print',
                    title: 'All Products',
                    className: 'btn btn-sm mr-1',
                    exportOptions: {
                        columns: 'th:not(:last-child)'
                    }
                }],
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        });
        $('#btnSearch').keyup(function () {
            search_table($(this).val());
        });
        function search_table(value) {
            $("#tblGov tr").each(function () {
                var found = 'false';
                $(this).each(function () {
                    if ($(this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0) {
                        found = 'true';
                    }
                });
                if (found == 'true') {
                    $(this).show();
                } else {
                    $(this).hide();
                }
            });
        };
    </script>
}