BaytonicECommerce/Controllers/ClientProductController.cs
using BaytonicECommerce.Models;
using BaytonicECommerce.Repository;
using BaytonicECommerce.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BaytonicECommerce.Controllers
{
    public class ClientProductController : BaseController
    {
        private readonly IProductRepository productRepository;
       
        private readonly IProductImageRepository productImageRepository;
        private readonly IProductDescriptionRepository productDescriptionRepository;

        public ClientProductController(IProductRepository _productRepository, IProductImageRepository _productImageRepository, IProductDescriptionRepository _productDescriptionRepository)
        {
            productRepository = _productRepository;
            productImageRepository = _productImageRepository;
            productDescriptionRepository = _productDescriptionRepository;
        }
        public IActionResult Index()
        {
            IEnumerable<VwproductWithCategoryName> vwproductWithCategoryNames = productRepository.GetAllProductsByCategoryName();
            return View(vwproductWithCategoryNames);
        }
        [HttpGet]
        [Route("/products/")]
        public IActionResult GetProductsByCategoryID(long id)
        {
            IEnumerable<Product> products = productRepository.GetAllByCategory(id);
            return View(products);
        }
        [Route("/search/")]
        public IActionResult GetProductsByTags(string tag)
        {
            IEnumerable<Product> products = productRepository.GetProductByTag(tag);
            return View(products);
        }
        [Route("/Offers/")]
        public IActionResult GetProductsByOffers(string tag)
        {
            IEnumerable<Product> products = productRepository.GetProductWithOffer();
            return View(products);
        }
        [HttpGet]
        public IActionResult GetAllProducts()
        {
            IEnumerable<Product> products = productRepository.GetAll();
            return View(products);
        }
        [HttpGet]
        public IActionResult GetProductsWithOffer()
        {
            IEnumerable<Product> products = productRepository.GetProductWithOffer();
            return View(products);
        }
        [HttpGet]
        public IActionResult GetProductsTopSeller()
        {
            IEnumerable<Product> products = productRepository.GetTopSellerProducts();
            return View(products);
        }
        [HttpGet]
        public IActionResult GetProductByIDQuickView(long id)
        {
            ProductDetailsVM productDetailsVM = new ProductDetailsVM()
            {
                product = productRepository.GetById(id),
                productDescriptions = productDescriptionRepository.GetProductDescriptions(id),
                ProductImages = productImageRepository.GetProductImgsByProductID(id)
            };
            return PartialView(productDetailsVM);
        }
        [HttpGet]
        [Route("/product-details/")]
        public IActionResult GetProductDetails(long id)
        {
            Product product = productRepository.GetById(id);
            ProductDetailsVM productDetailsVM = new ProductDetailsVM()
            {
                product = product,
                productDescriptions = productDescriptionRepository.GetProductDescriptions(id),
                ProductImages = productImageRepository.GetProductImgsByProductID(id),
                relatedProducts = productRepository.GetTopTenProductsOfCategory(product.CategoryId)
            };
            return View(productDetailsVM);
        }
    }
}

BaytonicECommerce/Views/ClientProduct/GetProductsByTags.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization
@inject IStringLocalizer<Resource> T

@{
    ViewData["Title"] = "GetProductsByCategoryID";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}
@model IEnumerable<Product>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/paginationjs/2.1.5/pagination.css" integrity="sha512-QmxybGIvkSI8+CGxkt5JAcGOKIzHDqBMs/hdemwisj4EeGLMXxCm9h8YgoCwIvndnuN1NdZxT4pdsesLXSaKaA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<div class="main-container container">
    <ul class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i></a></li>
        <!-- Cat. Na -->
        <li><a href="#">@T["SearchResult"]</a></li>
    </ul>

    <div class="row">

        <!--Middle Part Start-->
        <div id="content" class="col-md-12 col-sm-12">
            <div class="products-category">
                <h3 class="title-category ">@T["SearchResult"]</h3>
                @*<div class="category-derc">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="banners">
                                <div>

                                    <a href="#"><img src="~/ClientTemplet/image/catalog/demo/category/img-cate.jpg" alt="img cate"><br></a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>*@
                <!-- Filters -->
                @*<div class="product-filter product-filter-top filters-panel">
                    <div class="row">

                        <div class="short-by-show form-inline text-right col-xs-12">
                            <div class="form-group short-by">
                                <label class="control-label" for="input-sort">Sort By:</label>
                                <select id="input-sort" class="form-control"
                                        onchange="location = this.value;">
                                    <option value="" selected="selected">Default</option>
                                    <option value="">Name (A - Z)</option>
                                    <option value="">Name (Z - A)</option>
                                    <option value="">Price (Low &gt; High)</option>
                                    <option value="">Price (High &gt; Low)</option>
                                </select>
                            </div>
                        </div>

                    </div>
                </div>*@
                <!-- //end Filters -->
                <!--changed listings-->
                @if (Model.Count() <= 0)
                {
                    <h1>@T["SorryNoSearchResult"]</h1>
                }
                else
                {
            <div class="products-list row nopadding-xs so-filter-gird">

                      @{int counter = 0;}
                <!-- Product start -->
                     <div class="row">
                    @foreach (var item in Model)
                    {
                        if (counter % 4 == 0)
                        {
                        @:</div><div class="row">
                        }
                        <div class="product-layout col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <div class="product-item-container">
                                <div class="left-block">
                                    <div class="product-image-container second_img">
                                        <a asp-action="GetProductDetails" asp-controller="ClientProduct" asp-route-id="@item.Id">
                                            <img src="@Url.Content(item.FirstImgUrl)" class="img-1 img-responsive" alt="image">
                                            <img src="@Url.Content(item.FirstImgUrl)" class="img-2 img-responsive" alt="image">
                                        </a>
                                    </div>
                                    @if (item.Offer > 0)
                                    {
                                        int presentage = (int)((item.Offer / item.Price) * 100) - 100;
                                        <div class="box-label"> <span class="label-product label-sale"> @presentage % </span></div>

                                    }
                                    <div class="button-group so-quickview cartinfo--left">
                                        <button type="button" class="addToCart btn-button" title="Add to cart" onclick="addToCart(@item.Id, '@item.NameE', '@item.NameA' , @item.Price,@item.Offer , '@item.FirstImgUrl', 1)">
                                            <i class="fa fa-shopping-basket"></i>
                                            <span>@T["Addtocart"] </span>
                                        </button>
                                        <button type="button" class="wishlist btn-button" title="Add to Wish List" onclick="AddToWishList(@item.Id)">
                                            <i class="fa fa-heart"></i><span>@T["AddtoWishList"]</span>
                                        </button>
                                        @*<button type="button" class="compare btn-button" title="Compare this Product " onclick="compare.add('60');">
                                    <i class="fa fa-refresh"></i><span>Compare this Product</span>
                                </button>*@
                                        <!--quickview-->
                                        <a class="iframe-link btn-button quickview quickview_handler visible-lg" asp-action="GetProductByIDQuickView" asp-controller="ClientProduct" asp-route-id="@item.Id" title="Quick view" data-fancybox-type="iframe"><i class="fa fa-eye"></i><span>Quick view</span></a>
                                        <!--end quickview-->
                                    </div>
                                </div>
                                <div class="right-block">
                                    <div class="caption">
                                        <div class="rating">
                                            <span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span>
                                            <span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span>
                                            <span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span>
                                            <span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span>
                                            <span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span>
                                        </div>
                                        @if (CultureInfo.CurrentCulture.Name.StartsWith("ar"))
                                        {
                                            <h4><a asp-action="GetProductDetails" asp-controller="ClientProduct" asp-route-id="@item.Id" title="@item.NameA" target="_self">@item.NameA</a></h4>
                                        }
                                        else
                                        {
                                            <h4><a asp-action="GetProductDetails" asp-controller="ClientProduct" asp-route-id="@item.Id" title="@item.NameE" target="_self">@item.NameE</a></h4>
                                        }
                                        <div class="price">
                                            @if (item.Offer > 0)
                                            {
                                                <span class="price-new">@item.Offer L.E</span>
                                                <span class="price-old">@item.Price L.E</span>
                                            }
                                            else
                                            {
                                                <span class="price-new">@item.Price L.E</span>

                                            }

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        counter++;
                    }
                </div>
                    <!-- Product End -->
                </div>
                }
                <!--// End Changed listings-->
                <div id="pagination-container" class="col-xs-12 text-right pull-right ">

                </div>


            </div>

        </div>


        <!--Middle Part End-->


    </div>
    <!--Middle Part End-->
</div>
@section Scripts{
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/simplePagination.js/1.6/jquery.simplePagination.min.js"></script>

    <script type="text/javascript">
        // Check if Cookie exists
        view = 'grid';
        if ($.cookie('display')) {
            view = $.cookie('display');
        } else {
            view = 'grid';
        }
        if (view) display(view);
        //--></script>



    <script>



        var items = $('.products-list .product-layout');
        var numitems = items.length;
        var perpage = 20;

        items.slice(perpage).hide();


        $('#pagination-container').pagination({
            items: numitems,
            itemsOnPage: perpage,
            prevText: "<",
            nextText: ">",
            onPageClick: function (pageNumber) {
                var showFrom = perpage * (pageNumber - 1);
                var showTo = showFrom + perpage;
                items.hide().slice(showFrom, showTo).show();

                $('body,html').animate({
                    scrollTop: 0
                }, 600);
            }
        });

    </script>
}