BaytonicECommerce/Controllers/AdminOfferController.cs
using BaytonicECommerce.Models;
using BaytonicECommerce.Repository;
using BaytonicECommerce.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BaytonicECommerce.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class AdminOfferController : BaseController
    {

        private IProductRepository productRepository;
        public AdminOfferController(IProductRepository _productRepository)
        {
            productRepository = _productRepository;
        }
        public IActionResult Index()
        {
            IEnumerable<Product> OfferProducts = productRepository.GetProductWithOffer();
            return View(OfferProducts);
        }
        [HttpGet]
        public IActionResult Create()
        {
            Product_OfferVM product_OfferVM = new Product_OfferVM();
            product_OfferVM.Products = productRepository.GetAll();
            return View(product_OfferVM);
        }
        [HttpPost]
        public IActionResult Create(Product_OfferVM product_OfferVM)
        {
            Product OldProduct = productRepository.GetById(product_OfferVM.product.Id);
            OldProduct.Offer = product_OfferVM.product.Offer;
            productRepository.Update(OldProduct);
            return RedirectToAction("Index");
        }
        //Get Product Price as a json result to be shown in offers using ajax
        public IActionResult GetProductPrice(long id)
        {
            Product Product = productRepository.GetById(id);
            decimal price = -1;
            if (Product!=null)
            {
                price = Product.Price;
            }
            return Json(price);
        }
        [HttpGet]
        public IActionResult Edit(long id)
        {
            Product product = new Product();
            product = productRepository.GetById(id);
            return View(product);
        }
        [HttpPost]
        public IActionResult Edit(Product product)
        {
            Product OldProduct = productRepository.GetById(product.Id);
            OldProduct.Offer = product.Offer;
            productRepository.Update(OldProduct);
            return RedirectToAction("Index");
        }
      
        public IActionResult Delete(long id)
        {
            Product OldProduct = productRepository.GetById(id);
            OldProduct.Offer = 0;
            productRepository.Update(OldProduct);
            return RedirectToAction("Index");
        }
    }
}

BaytonicECommerce/Views/AdminOffer/Create.cshtml
@model Product_OfferVM
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container-fluid">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h5 style="color:gray">Product-Offer</h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="SysOffer">Product-Offer</a></li>
                        <li class="breadcrumb-item active">Add New Product-Offer</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="card card-info" style="margin:10px">
        <div class="card-header">
            <h3 class="card-title">New Product-Offer</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" asp-controller="AdminOffer" method="post" asp-action="Create">
            <div class="card-body">
                <div class="form-group row">
                    @*@Html.LabelFor(x => Model.product.Id, htmlAttributes: new { @class = "col-sm-2 col-form-label" })*@
                    <label class="col-sm-2 col-form-label">Product </label>
                    <div class="col-sm-10">
                        
                        @Html.DropDownListFor(x => Model.product.Id, new SelectList(Model.Products, "Id", "NameE"),"select product", htmlAttributes: new { @class = "form-control", id = "product_Id" })
                                          
    @*<input asp-for="ProductId" class="form-control" placeholder="Product ID" required>*@
                    </div>
                    <span asp-validation-for="product.Id" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Old Price</label>
                    <div class="col-sm-10">
                        <input id="oldPrice" type="text" class="form-control" readonly>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">persentage </label>
                    <div class="col-sm-9">
                        <input type="number" id="offerPersentage" onchange="persentagechange()" class="form-control" max="100" min="0" placeholder="Offer Persentage From 1-100 ">
                    </div>
                    <label class="col-sm-1 col-form-label">% </label>
                    @*<span asp-validation-for="product.Offer" class="text-danger"></span>*@
                </div>
                <div class="form-group row">
                    <label asp-for="product.Offer" class="col-sm-2 col-form-label">New Price</label>
                    <div class="col-sm-10">
                        <input type="number" id="offerNewPrice" asp-for="product.Offer" class="form-control" placeholder="New Price" readonly required>
                    </div>
                    
                </div>


                @*<div class="form-group row">
            <div class="custom-control custom-checkbox">
                <input asp-for="Offer.IsActive" class="custom-control-input" type="checkbox" style="margin-right:10px">
                <label asp-for="Offer.IsActive" class="custom-control-label">Available</label>
                <span asp-validation-for="Offer.IsActive" class="text-danger"></span>
            </div>

        </div>*@
            </div>

            @*<div class="form-group row">
                    <label asp-for="product.Isactive" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <input asp-for="product.Isactive" type="checkbox" class="form-control">
                    </div>
                    <span asp-validation-for="product.Isactive" class="text-danger"></span>
                </div>*@

            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-info"> <i class="far fa-save mr-1"></i> Save</button>
                <a asp-action="Index" asp-controller="AdminOffer" class="btn btn-default float-right">Cancel</a>
            </div>

            <!-- /.card-footer -->
        </form>
    </div>
</div>
@section Scripts{
    <script>
        $('#product_Id').on('change', function () {
            
            var productId= $("#product_Id option:selected").val();
        $.ajax({
            url: '@Url.Action("GetProductPrice", "AdminOffer")',
            type: 'GET',
            cache: false,
           data: { id: productId}
        }).done(function (result) {
            console.log(result);

            $('#oldPrice').val(result);
        });
    });
    function persentagechange()
    {
        var persentage = document.getElementById('offerPersentage').value;
        var oldPrice = document.getElementById('oldPrice').value;
        console.log(persentage);
        console.log(oldPrice);
        if (persentage > 0 && persentage<100)  {
            document.getElementById('offerNewPrice').value = (oldPrice - ((persentage / 100) * oldPrice));
        }
    }
    </script>
   
}

BaytonicECommerce/Views/AdminOffer/Edit.cshtml
@model Product
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container-fluid">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h5 style="color:gray">Product-Offer</h5>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="AdminOffer">Product-Offer</a></li>
                        <li class="breadcrumb-item active">Edit Product-Offer</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="card card-info" style="margin:10px">
        <div class="card-header">
            <h3 class="card-title">Edit Product-Offer</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" asp-controller="AdminOffer" method="post" asp-action="Edit">
            <div class="card-body">
                <div class="form-group row">
                    <label asp-for="NameE" class="col-sm-2 col-form-label">Product</label>
                    <div class="col-sm-10">
                        <input asp-for="NameE" class="form-control" readonly required>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Old Price</label>
                    <div class="col-sm-10">
                        <input id="oldPrice" type="text" class="form-control" value="@Model.Price" readonly>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">persentage </label>
                    <div class="col-sm-9">
                        <input type="number" id="offerPersentage" onchange="persentagechange()" class="form-control" max="100" min="0" placeholder="Offer Persentage From 1-100 "value="@(100-((100*Model.Offer)/Model.Price))">
                    </div>
                    <label class="col-sm-1 col-form-label">% </label>
                    @*<span asp-validation-for="product.Offer" class="text-danger"></span>*@
                </div>
                <div class="form-group row">
                    <label asp-for="Offer" class="col-sm-2 col-form-label">New Price</label>
                    <div class="col-sm-10">
                        <input type="number" id="offerNewPrice" asp-for="Offer" class="form-control" placeholder="New Price" readonly required>
                    </div>

                </div>


                @*<div class="form-group row">
            <div class="custom-control custom-checkbox">
                <input asp-for="Offer.IsActive" class="custom-control-input" type="checkbox" style="margin-right:10px">
                <label asp-for="Offer.IsActive" class="custom-control-label">Available</label>
                <span asp-validation-for="Offer.IsActive" class="text-danger"></span>
            </div>

        </div>*@
            </div>

            
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-info"> <i class="far fa-save mr-1"></i> Save</button>
                <a asp-action="Index" asp-controller="AdminOffer" class="btn btn-default float-right">Cancel</a>
            </div>

            <!-- /.card-footer -->
        </form>
    </div>
</div>
@section Scripts{
    <script>
        @*$('#product_Id').on('change', function () {

            var productId= $("#product_Id option:selected").val();
        $.ajax({
            url: '@Url.Action("GetProductPrice", "AdminOffer")',
            type: 'GET',
            cache: false,
           data: { id: productId}
        }).done(function (result) {
            console.log(result);

            $('#oldPrice').val(result);
        });
    });*@
    function persentagechange()
    {
        var persentage = document.getElementById('offerPersentage').value;
        var oldPrice = document.getElementById('oldPrice').value;
        console.log(persentage);
        console.log(oldPrice);

        if (persentage > 0 && persentage < 100) {
            document.getElementById('offerNewPrice').value = (oldPrice - ((persentage / 100) * oldPrice));
        }
    }
    </script>

}

BaytonicECommerce/Views/AdminOffer/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@model IEnumerable<Product>
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h3 style="color:gray">Offers</h3>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active">Offers</li>

                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div>
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">


                            <div class="row mb-3">
                                <div class="col-12">
                                    <div class="input-group input-group-lg">
                                        <input type="search" id="btnSearch" class="form-control form-control-sm" placeholder="Type your keywords here">
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-sm btn-default">
                                                <i class="fa fa-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <a asp-action="Create" asp-controller="AdminOffer" type="button" class="btn btn-info float-right btn-sm"> <i class="fas fa-plus"></i> New</a>

                                    <table id="example1" class="table table-bordered  table-striped mt-3">
                                        <thead class="table-primary">
                                            <tr>
                                                <th>Product English Name</th>
                                                <th>Product Arabic Name</th>
                                                <th>Old Price</th>
                                                <th>Offer % </th>
                                                <th>New Price</th>
                                                <th>#</th>
                                            </tr>
                                        </thead>
                                        <tbody id="tblProduct" class="table-sm">
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>@item.NameE</td>
                                                    <td>@item.NameA</td>
                                                    <td>@item.Price</td>
                                                    <td>@(100-((item.Offer * 100) /item.Price))  %</td>
                                                    <td>@item.Offer</td>
                                                    <td>

                                                        <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
                                                            <i class="fa fa-ellipsis-h" aria-hidden="true"></i>
                                                        </a>
                                                        <div class="dropdown-menu" style="">
                                                            <a asp-controller="AdminOffer" asp-action="Edit" asp-route-id="@item.Id" class=" nav-link" tabindex="-1"><i class="fas fa-edit"></i> Edit</a>
                                                            <a asp-action="Delete" asp-controller="AdminOffer" asp-route-id="@item.Id"class="nav-link" tabindex="-1" style="color:red"> <i class="far fa-trash-alt"></i> Delete</a>

                                                        </div>

                                                    </td>

                                                </tr>

                                            }
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
    </div>
    </div>

</section>
@section Scripts{
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false, "searching": false,
                buttons: [{
                    extend: 'excel',
                    text: ' Export',
                    title: 'All Products',
                    className: 'btn btn-sm mr-1',
                    exportOptions: {
                        columns: 'th:not(:last-child)'
                    }
                }, {
                        extend: 'print',
                        text: 'print',
                        title: 'All Products',
                        className: 'btn btn-sm mr-1',
                        exportOptions: {
                            columns: 'th:not(:last-child)'
                        }
                    }],
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        });
        $('#btnSearch').keyup(function () {
            search_table($(this).val());
        });
        function search_table(value) {
            $("#tblProduct tr").each(function () {
                var found = 'false';
                $(this).each(function () {
                    if ($(this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0) {
                        found = 'true';
                    }
                });
                if (found == 'true') {
                    $(this).show();
                } else {
                    $(this).hide();
                }
            });
            };
    </script>
}